# Generated by Django 2.2.2 on 2021-03-03 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mainBody', models.TextField()),
                ('newsTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('newsWriter', models.CharField(max_length=20)),
                ('newsChecker', models.CharField(max_length=20, null=True)),
                ('newsType', models.CharField(max_length=10)),
                ('newsScanNumber', models.IntegerField(default=0)),
                ('newsDownTitle', models.CharField(max_length=255, null=True)),
                ('contentKeywords', models.CharField(max_length=255)),
                ('newsState', models.IntegerField()),
                ('ready', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-newsTime'],
            },
        ),
    ]
