# Generated by Django 2.2.2 on 2021-02-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=21, null=True)),
                ('stu_id', models.CharField(max_length=255, null=True)),
                ('stu_sex', models.CharField(max_length=2, null=True)),
                ('stu_iden', models.CharField(max_length=20, null=True)),
                ('stu_pic', models.ImageField(null=True, upload_to='img')),
                ('stu_intro', models.TextField(null=True)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
