# Generated by Django 2.2.2 on 2021-03-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('announceTime', models.DateField(null=True)),
                ('announceWriter', models.CharField(max_length=20, null=True)),
                ('announceOrigin', models.CharField(max_length=20, null=True)),
                ('mainBody', models.TextField(null=True)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
